# Generated by Django 4.0.6 on 2022-08-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_alter_emprestimo_data_emprestimo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['data_emprestimo']},
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='avaliacao',
            field=models.CharField(choices=[('B', 'Bom'), ('M', 'Médio'), ('R', 'Ruim')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
