# Generated by Django 4.0.6 on 2022-08-12 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0002_alter_usuario_senha'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='nome',
            new_name='usuario',
        ),
    ]
